### PR TITLE
Technology Decision! Error Reporting

### PR DESCRIPTION
**Pull request by brycemcd**
See the docs. Adding error reporting to the constituent app
for a variety of reasons.

[Trello Ticket](https://trello.com/c/4g6enebb)

## Prerequisite PRs
None

## Dependent PRs
None

## New ENV Vars
None

## Notes for Reviewer

Again, I'd like everyone to take a look at this PR so we're all aware of what technology decision we're making and why we're making it. _Please_ feel free to argue any of the decision criteria and the result.

I'd like to get this merged in and started working on deploying the solution by September 8th, 2018.

### CODE REVIEW

**Comment by andrezafeu** [comment]
I think Sentry is pretty Robust.  I haven't worked with the other options yet (and barely with Sentry to be honest) but it does have everything we need. Unless someone has had some bad experience with it in the past, it sounds like a good choice to me!
I remember being a little bit overwhelmed by the email notifications, but it was probably just a configuration issue.

**Comment by brycemcd** [comment]
Cool, great to hear. Any opinions @chrisruenes1 and @e91096 ?

**Comment by e91096** [comment]
you make a great case for sentry--i'm for it!

**Comment by brycemcd** [comment]
Sentry set up in prod @ https://sentry.io/pocketlobby-constituents/pocketlobby-constituents/ . We can set up staging a little later.

**Pull request merged**
